name: syamsun
description: "Prayer times for muslims"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  adhan: ^2.0.0+1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_time_picker_spinner: ^2.0.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  google_fonts: ^6.2.1
  home_widget: ^0.7.0
  intl: ^0.20.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.1
  timezone: ^0.10.0
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true